name: test-anvi-bam

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y samtools bwa

    - name: Install micromamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        chmod +x bin/micromamba
        ./bin/micromamba shell init -s bash -p ~/micromamba
        echo "export PATH=~/micromamba/bin:\$PATH" >> ~/.bashrc
        source ~/.bashrc

    - name: Create and activate environment
      run: |
        micromamba create -n myenv -c conda-forge -c bioconda "seqfu>1.10"
        micromamba activate myenv

    - name: Run make
      run: |
        seqfu version
