name: test-anvi-bam

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install BWA and Samtools
      run: |
        sudo apt-get update
        sudo apt-get install -y bwa samtools
    - name: Download anvio package
      run: |
        curl -L https://github.com/merenlab/anvio/releases/download/v8/anvio-8.tar.gz --output anvio-8.tar.gz

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.4.5-0'
        environment-file: environment.yml
        activate-environment: bioinfo-env
        init-shell: bash
    - name: Install anvio
      run: |
        eval "$(micromamba shell hook --shell bash)"
        micromamba activate bioinfo-env
        pip install anvio-8.tar.gz
        anvi-help --help
