name: test-anvi-bam

on:
  workflow_dispatch:  # This event allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y samtools bwa

    - uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-name: test-env
        create-args: >-
          python=3.10
          seqfu=1.20.0
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Import numpy in micromamba environment (pwsh)
      run: seqfu version
    
